### ISSUE TITLE
width issue in buildEdge

### ISSUE THREAD

**Issue by vikon72** [jhk0530/shinyCyJS#1]
Once I set "width" parameter with buildEdge,there will be an error.Warning: Error in buildEdge: width must be numeric.But.Is there an issue with the Arguments?

**Comment by jhk0530** [comment]
thanks for using this package.

could you give me example code that you have tried?! it will be helpful very much.

**Comment by vikon72** [comment]
Thanks for your reply.The example code and files were upload to my repositories:
https://github.com/vikon72/shinyCyJSfile.git

Thanks in advance!

**Comment by jhk0530** [comment]
during weekend I'll check it. thanks

**Comment by jhk0530** [comment]
Hi, I found problem and it solved. :rocket: 

below is result figure with your code 
using `width = edge_data()[,"edge_width"],`

![image](https://user-images.githubusercontent.com/6457691/101735022-90ca0a00-3b04-11eb-8705-7a78c8808c08.png)

try re-install from repository **(not cran version)** like using `install_github` and let me know if any problem.

Thanks.

**Comment by vikon72** [comment]
Fine,It is useful to re-install from repository.

Thanks for your help.
