### ISSUE TITLE
package submission in bioconductor

### ISSUE THREAD

**Issue by jhk0530** [jhk0530/shinyCyJS#16]

**Comment by jhk0530** [comment]
You may help this issue. @assaron 

Thanks.

**Comment by assaron** [comment]
@jhk0530 Not sure, what you mean. You already have the package in CRAN, so I don't think there is a purpose to have it in Bioconductor? The packages in Bioconductor can depend on CRAN packages without problem. Moreover, you can't have package with the same name to be simultaneously in CRAN and Bioconductor.
