### ISSUE TITLE
Download Picture

### ISSUE THREAD

**Issue by JasonTan-code** [jhk0530/shinyCyJS#5]
Hi Dr Kim.

I would like to appreciate your work on shinyCyJS. It's much easier to use than cyjShiny and I am integrating your package into my bioinformatic shiny web. Is it possible to allow users to download the picture? That will be a very helpful feature. 

Thanks again for the good work.

**Comment by jhk0530** [comment]
what could be different between taking a screenshot?

**Comment by jhk0530** [comment]
Hi, @JasonTan-code 

This repository will move to [my personal repository](https://github.com/jhk0530/shinycyjs) since this organization doesn't maintained.

so I'll copy this issue to there and close in here.

Thanks

Kim

**Comment by jhk0530** [comment]
I'm trying to add PNG feature. 
But until then, you can use below [Georg Schwarz](https://stackoverflow.com/users/12256497/georg-schwarz)'s [option](https://stackoverflow.com/questions/39168928/cytoscape-save-graph-as-image-by-button). 

Go to dev mode in chrome. 

enter below code to console.

```
const pngBlob = await cy.png({
  output: 'blob-promise',
});

const fileName = 'myfile.png';
const downloadLink = document.createElement('a');
downloadLink.href = URL.createObjectURL(pngBlob);
downloadLink.download = fileName;
downloadLink.click();
```

**Comment by jhk0530** [comment]
updated with v.1.2.0.

check [this](https://jhk0530.github.io/shinyCyJS/articles/export-png.html)
